use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Top-level application configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    #[serde(default)]
    pub server: ServerConfig,
    #[serde(default)]
    pub output: OutputConfig,
    #[serde(default)]
    pub display: DisplayConfig,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            server: ServerConfig::default(),
            output: OutputConfig::default(),
            display: DisplayConfig::default(),
        }
    }
}

impl AppConfig {
    /// Create a new config with server credentials.
    #[allow(dead_code)]
    pub fn new(url: String, api_key: String) -> Self {
        Self {
            server: ServerConfig { url, api_key },
            ..Default::default()
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    #[serde(default = "default_server_url")]
    pub url: String,
    #[serde(default)]
    pub api_key: String,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            url: default_server_url(),
            api_key: String::new(),
        }
    }
}

fn default_server_url() -> String {
    "https://app.pipelite.io".to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct OutputConfig {
    pub format: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DisplayConfig {
    pub no_color: Option<bool>,
}

/// Determine the config file path.
///
/// Checks `PIPELITE_CONFIG` env var first, then falls back to `~/.pipelite/config.toml`.
pub fn config_path() -> Result<PathBuf> {
    if let Ok(custom) = std::env::var("PIPELITE_CONFIG") {
        return Ok(PathBuf::from(custom));
    }

    let home = std::env::var("HOME").context(
        "Could not determine home directory. Set HOME or PIPELITE_CONFIG environment variable.",
    )?;

    Ok(PathBuf::from(home)
        .join(".pipelite")
        .join("config.toml"))
}

/// Load configuration from a file path, falling back to defaults.
///
/// After loading the file (or defaults if file doesn't exist), env vars are
/// merged with higher precedence: `PIPELITE_API_KEY` and `PIPELITE_SERVER_URL`.
pub fn load_config(path: Option<&Path>) -> Result<AppConfig> {
    let config_file = match path {
        Some(p) => p.to_path_buf(),
        None => config_path()?,
    };

    let mut config = if config_file.exists() {
        let content = std::fs::read_to_string(&config_file)
            .with_context(|| format!("Failed to read config file: {}", config_file.display()))?;
        toml::from_str::<AppConfig>(&content)
            .with_context(|| format!("Failed to parse config file: {}", config_file.display()))?
    } else {
        AppConfig::default()
    };

    // Env vars override config file values
    if let Ok(api_key) = std::env::var("PIPELITE_API_KEY") {
        config.server.api_key = api_key;
    }
    if let Ok(server_url) = std::env::var("PIPELITE_SERVER_URL") {
        config.server.url = server_url;
    }

    Ok(config)
}

/// Write configuration to a file with 0600 permissions on Unix.
///
/// Creates parent directories if they don't exist. Uses the commented
/// template format for human readability.
pub fn write_config(path: &Path, config: &AppConfig) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create config directory: {}", parent.display()))?;
    }

    let content = generate_commented_config(config);

    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(path)
            .with_context(|| format!("Failed to create config file: {}", path.display()))?;
        file.write_all(content.as_bytes())?;
    }

    #[cfg(not(unix))]
    {
        std::fs::write(path, content)
            .with_context(|| format!("Failed to write config file: {}", path.display()))?;
    }

    Ok(())
}

/// Generate a commented config TOML template with current values.
pub fn generate_commented_config(config: &AppConfig) -> String {
    let format_line = match &config.output.format {
        Some(fmt) => format!("format = \"{}\"", fmt),
        None => "# format = \"table\"".to_string(),
    };

    let no_color_line = match config.display.no_color {
        Some(val) => format!("no_color = {}", val),
        None => "# no_color = false".to_string(),
    };

    format!(
        r#"# Pipelite CLI Configuration
# Generated by `pipelite init`

[server]
# Pipelite CRM server URL
url = "{url}"
# API key for authentication (keep this secret!)
api_key = "{api_key}"

[output]
# Default output format: json, table, csv, plain
{format_line}

[display]
# Disable colored output (also: NO_COLOR env var or --no-color flag)
{no_color_line}
"#,
        url = config.server.url,
        api_key = config.server.api_key,
        format_line = format_line,
        no_color_line = no_color_line,
    )
}

/// Set a configuration value using a dotted key path.
///
/// Uses `toml_edit` to preserve comments and formatting in the config file.
pub fn set_config_value(path: &Path, key: &str, value: &str) -> Result<()> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("Could not read config file: {}", path.display()))?;

    let mut doc = content
        .parse::<toml_edit::DocumentMut>()
        .context("Config file has invalid TOML")?;

    let parts: Vec<&str> = key.split('.').collect();
    match parts.as_slice() {
        [section, field] => {
            doc[*section][*field] = toml_edit::value(value);
        }
        [field] => {
            doc[*field] = toml_edit::value(value);
        }
        _ => anyhow::bail!(
            "Invalid key format: {key}. Use section.key (e.g., output.format)"
        ),
    }

    // Write back preserving comments and formatting
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(path)
            .with_context(|| format!("Could not write config file: {}", path.display()))?;
        file.write_all(doc.to_string().as_bytes())?;
    }

    #[cfg(not(unix))]
    {
        std::fs::write(path, doc.to_string())
            .with_context(|| format!("Could not write config file: {}", path.display()))?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Helper to safely set env var in tests (unsafe in Rust 2024 edition).
    unsafe fn set_env(key: &str, val: &str) {
        unsafe { std::env::set_var(key, val) };
    }

    /// Helper to safely remove env var in tests (unsafe in Rust 2024 edition).
    unsafe fn remove_env(key: &str) {
        unsafe { std::env::remove_var(key) };
    }

    #[test]
    fn default_config_has_expected_values() {
        let config = AppConfig::default();
        assert_eq!(config.server.url, "https://app.pipelite.io");
        assert!(config.server.api_key.is_empty());
        assert!(config.output.format.is_none());
        assert!(config.display.no_color.is_none());
    }

    #[test]
    fn load_and_save_roundtrip() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");

        let config = AppConfig::new(
            "https://crm.example.com".to_string(),
            "pk_test_abc123".to_string(),
        );

        write_config(&path, &config).unwrap();

        // Clear env vars that could interfere
        unsafe {
            remove_env("PIPELITE_API_KEY");
            remove_env("PIPELITE_SERVER_URL");
        }

        let loaded = load_config(Some(&path)).unwrap();
        assert_eq!(loaded.server.url, "https://crm.example.com");
        assert_eq!(loaded.server.api_key, "pk_test_abc123");
    }

    #[test]
    fn env_var_precedence_api_key() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");

        let config = AppConfig::new(
            "https://crm.example.com".to_string(),
            "file_key".to_string(),
        );
        write_config(&path, &config).unwrap();

        // Set env var that should override
        unsafe { set_env("PIPELITE_API_KEY", "env_key") };
        let loaded = load_config(Some(&path)).unwrap();
        assert_eq!(loaded.server.api_key, "env_key");

        // Clean up
        unsafe { remove_env("PIPELITE_API_KEY") };
    }

    #[test]
    fn env_var_precedence_server_url() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");

        let config = AppConfig::new(
            "https://file-url.example.com".to_string(),
            "key".to_string(),
        );
        write_config(&path, &config).unwrap();

        unsafe { set_env("PIPELITE_SERVER_URL", "https://env-url.example.com") };
        let loaded = load_config(Some(&path)).unwrap();
        assert_eq!(loaded.server.url, "https://env-url.example.com");

        unsafe { remove_env("PIPELITE_SERVER_URL") };
    }

    #[test]
    fn load_missing_file_returns_defaults() {
        unsafe {
            remove_env("PIPELITE_API_KEY");
            remove_env("PIPELITE_SERVER_URL");
        }

        let dir = TempDir::new().unwrap();
        let path = dir.path().join("nonexistent.toml");

        let config = load_config(Some(&path)).unwrap();
        assert_eq!(config.server.url, "https://app.pipelite.io");
        assert!(config.server.api_key.is_empty());
    }

    #[cfg(unix)]
    #[test]
    fn file_permissions_0600() {
        use std::os::unix::fs::PermissionsExt;

        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");

        let config = AppConfig::default();
        write_config(&path, &config).unwrap();

        let metadata = std::fs::metadata(&path).unwrap();
        let mode = metadata.permissions().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "Config file should have 0600 permissions, got {:o}",
            mode
        );
    }

    #[test]
    fn set_dotted_path_modifies_correct_key() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");

        let config = AppConfig::default();
        write_config(&path, &config).unwrap();

        set_config_value(&path, "output.format", "json").unwrap();

        // Read back and verify
        unsafe {
            remove_env("PIPELITE_API_KEY");
            remove_env("PIPELITE_SERVER_URL");
        }
        let loaded = load_config(Some(&path)).unwrap();
        assert_eq!(loaded.output.format.as_deref(), Some("json"));
    }

    #[test]
    fn set_config_preserves_comments() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");

        let config = AppConfig::default();
        write_config(&path, &config).unwrap();

        set_config_value(&path, "output.format", "json").unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        // Comments from the original template should still be present
        assert!(content.contains("# Pipelite CLI Configuration"));
        assert!(content.contains("# API key for authentication"));
    }

    #[test]
    fn config_path_env_override() {
        unsafe { set_env("PIPELITE_CONFIG", "/tmp/custom/config.toml") };
        let path = config_path().unwrap();
        assert_eq!(path, PathBuf::from("/tmp/custom/config.toml"));
        unsafe { remove_env("PIPELITE_CONFIG") };
    }

    #[test]
    fn default_config_path() {
        unsafe { remove_env("PIPELITE_CONFIG") };
        let path = config_path().unwrap();
        let home = std::env::var("HOME").unwrap();
        assert_eq!(
            path,
            PathBuf::from(home).join(".pipelite").join("config.toml")
        );
    }

    #[test]
    fn generate_commented_config_has_all_sections() {
        let config = AppConfig::new(
            "https://test.example.com".to_string(),
            "pk_test_123".to_string(),
        );
        let output = generate_commented_config(&config);

        assert!(output.contains("[server]"));
        assert!(output.contains("[output]"));
        assert!(output.contains("[display]"));
        assert!(output.contains("https://test.example.com"));
        assert!(output.contains("pk_test_123"));
        assert!(output.contains("# Pipelite CLI Configuration"));
    }

    #[test]
    fn generate_commented_config_with_set_values() {
        let mut config = AppConfig::default();
        config.output.format = Some("json".to_string());
        config.display.no_color = Some(true);

        let output = generate_commented_config(&config);
        assert!(output.contains("format = \"json\""));
        assert!(output.contains("no_color = true"));
    }

    #[test]
    fn set_invalid_key_format_returns_error() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");

        let config = AppConfig::default();
        write_config(&path, &config).unwrap();

        let result = set_config_value(&path, "a.b.c", "value");
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Invalid key format"));
    }
}
